### PR TITLE
13 add cook times

### PR DESCRIPTION
**Pull request by katharinap**

### CODE REVIEW

**Comment by bamohan** [comment]
LGTM! I am not clear on what active_time means though. Is it prep time or cook time? I didn't understand the difference between total_time and active_time.

**Comment by katharinap** [comment]
active_time is the time to have to actively do something.  It's mostly the same as prep time.  If you e.g. make a veggie soup, you don't spend much time in the kitchen, just for cutting and getting everything together.  After that, it cooks for quite a while but you are free to do something else.  So this recipe has a rather short active time but a long total time.  Whereas, if you cook something that needs your constant attention, active and total time would be the same.

**Comment by bamohan** [comment]
Do these fields need to be added to new_recipe?

**Comment by katharinap** [comment]
I'm not super happy with how this information shows up in the recipes#index view.  Do you have a better idea?  How do you feel about abandoning the table in that view and creating something similar to http://www.isachandra.com/recipes/ instead?  This makes interactive sorting impossible though (we do have an issue to add dataTables to the index view) and we might want to wait with that until we have the search functionality.

**Comment by bamohan** [comment]
That will be nice. That means we should have a default picture if no picture is uploaded. Also, wonder if we should add some more features before prettying up. But ok either way

**Comment by katharinap** [comment]
Let's keep it the way it is for now until we have a better idea of what the index page should look like and which features it will have.  I can live with a slightly ugly page for now :)

Should I merge it then?  Or would you like some more time to look at it?

**Comment by bamohan** [comment]
LGTM

**Comment by katharinap** [comment]
resolves #13

**Pull request merged**
