### PR TITLE
[#4] add tagging

### PR DESCRIPTION
**Pull request by bamohan**
- Add tagging ability for recipes - CRUD 

This is a first crude version. The next version is going to have the ability to auto-complete and search by tags.

### CODE REVIEW

**Comment by katharinap** [comment]
Very nice.  

I only have question - why does the User model have acts_as_tagger?  I do not see that being used/set anywhere.

**Comment by bamohan** [comment]
acts_as_tagger will be used when we do auto-complete. We will just have 'tags' of the user auto-complete possibly

**Comment by katharinap** [comment]
But so far, the association between user and tag does not happen, right?

**Comment by bamohan** [comment]
Not yet
thx

**Comment by katharinap** [comment]
Should we then comment it out for now?  To make it obvious that some code needs to change before there can be an association between users and tags?

If you want to leave it the way it is, that's fine with me as well.

Feel free to merge it.

**Pull request merged**
